[project]
name        = "hook"
description = "Common hatchling hook used in projects"
authors     = [{name="Tremeschin"}]
version     = "1.0.0"
license     = "MIT"

[project.entry-points.hatch]
plugin = "hook"
